name: KeyLocker-VS.Code
 
on: 
  workflow_dispatch:
 
jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
 
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4 
     
      - name: Install DigiCert Client tools from Github Custom Actions marketplace
        uses: digicert/ssm-code-signing@v1.0.0
   
      - name: Set up certificate 
        run: | 
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > /d/Certificate_pkcs12.p12 
        shell: bash  
        
      - name: Set variables 
        id: variables 
        run: | 
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT 
          echo "SM_HOST=${{ secrets.SM_HOST }}" >> "$GITHUB_ENV" 
          echo "SM_API_KEY=${{ secrets.SM_API_KEY }}" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_FILE=D:\\Certificate_pkcs12.p12" >> "$GITHUB_ENV" 
          echo "SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}" >> "$GITHUB_ENV" 
        shell: bash
 
      - name: Healthcheck      
        run: |
           smctl healthcheck
        shell: cmd
 
      
      - name: Windows CertSync
        run: |
           smctl windows certsync
        shell: cmd

      - name: Signing using certificate fingerprint      
        run: |
           smctl sign --fingerprint ${{ secrets.SM_CODE_SIGNING_CERT_SHA1_HASH }} --input 'C:\Users\lakhiwe.zaleni\Documents\Files\Icons.dll' --config-file 'C:\Program Files\DigiCert\Click-to-sign\pkcs11properties.cfg'
        shell: cmd

      
      - name: Signing using keypair alias
        run: |
           smctl sign --keypair-alias key_1303848249 --input 'C:\Users\lakhiwe.zaleni\Documents\Files\Icons.dll' --config-file 'C:\Program Files\DigiCert\Click-to-sign\pkcs11properties.cfg'
        shell: cmd
